version: '2'
services:
  app:
    extends:
      file: docker-compose.base.yml
      service: app
  node:
    extends:
      file: docker-compose.base.yml
      service: node
  redis:
    extends:
      file: docker-compose.base.yml
      service: redis
networks:
  laraveldocker:
    driver: "bridge"
volumes:
  postgresdata:
    driver: "local"
  redisdata:
    driver: "local"
