version: '2'
services:
  app:
    extends:
      file: docker-compose.base.yml
      service: app
    ports:
     - "${APP_PORT}:80"
    environment:
      APP_ENV: ${APP_ENV}
      XDEBUG_HOST: ${XDEBUG_HOST}
  node:
    extends:
      file: docker-compose.base.yml
      service: node
  postgres:
    extends:
        file: docker-compose.base.yml
        service: postgres
    ports:
     - "${DB_PORT}:5432"
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASS}"
  redis:
    extends:
      file: docker-compose.base.yml
      service: redis
networks:
  laraveldocker:
    driver: "bridge"
volumes:
  postgresdata:
    driver: "local"
  redisdata:
    driver: "local"
